export const FETCH = {
  TODOLIST: {
    START: 'FETCH_TODOLIST_START',
    SUCCESS: 'FETCH_TODOLIST_SUCCESS',
    FAILURE: 'FETCH_TODOLIST_FAILURE',
  },
  CREATE_TODO: {
    START: 'FETCH_CREATE_TODO_START',
    SUCCESS: 'FETCH_CREATE_TODO_SUCCESS',
    FAILURE: 'FETCH_CREATE_TODO_FAILURE',
  },
  REMOVE_TODO: {
    START: 'FETCH_REMOVE_TODO_START',
    SUCCESS: 'FETCH_REMOVE_TODO_SUCCESS',
    FAILURE: 'FETCH_REMOVE_TODO_FAILURE',
  },
  EDIT_TODO: {
    START: 'FETCH_EDIT_TODO_START',
    SUCCESS: 'FETCH_EDIT_TODO_SUCCESS',
    FAILURE: 'FETCH_EDIT_TODO_FAILURE',
  },
  FILTERED_TODOLIST: {
    START: 'FETCH_FILTERED_TODOLIST_START',
    SUCCESS: 'FETCH_FILTERED_TODOLIST_SUCCESS',
    FAILURE: 'FETCH_FILTERED_TODOLIST_FAILURE',
  }
};
