export const FETCH = {
  ENTITY: {
    START: 'FETCH_ENTITY_START',
    SUCCESS: 'FETCH_ENTITY_SUCCESS',
    FAILURE: 'FETCH_ENTITY_FAILURE',
  },
  TODOLIST: {
    START: 'FETCH_TODOLIST_START',
    SUCCESS: 'FETCH_TODOLIST_SUCCESS',
    FAILURE: 'FETCH_TODOLIST_FAILURE',
  }
};
